/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'bg-[#0C0C0E]',
    'bg-[#131316]',
    'bg-[#1C1C21]',
    'bg-[#222228]',
    'hover:bg-[#1C1C21]',
    'hover:bg-[#222228]',
    'border-[#26262B]',
    'border-[#303037]',
    'border-[#1C1C21]',
    'text-emerald-400',
    'text-emerald-500',
    'text-red-400',
    'text-red-500',
    'text-amber-400',
    'text-amber-500',
    'text-indigo-400',
    'text-indigo-300',
    'bg-indigo-600',
    'hover:bg-indigo-500',
    'bg-red-950',
    'hover:bg-red-950',
    'border-red-900',
    'hidden',
    'md:table-cell',
    'lg:table-cell',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
      },
      colors: {
        surface: {
          DEFAULT: '#0C0C0E',
          card: '#131316',
          elevated: '#1C1C21',
          hover: '#222228',
        },
        'app-border': {
          DEFAULT: '#26262B',
          light: '#303037',
        },
        asset: {
          stock: '#818CF8',
          crypto: '#A78BFA',
          cash: '#34D399',
          funds: '#60A5FA',
          loan: '#FBBF24',
          other: '#9CA3AF',
        },
        purpose: {
          compounder: '#818CF8',
          income: '#34D399',
          liquidity: '#60A5FA',
          opportunity: '#F472B6',
          store: '#FBBF24',
          strategic: '#F87171',
        },
      },
    },
  },
  plugins: [],
};
